/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/lambo.glb 
Author: Steven Grey (https://sketchfab.com/Steven007)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-urus-2650599973b649ddb4460ff6c03e4aa2
Title: Lamborghini Urus
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";

import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { useFrame } from "@react-three/fiber";
gsap.registerPlugin(useGSAP);

export function Lambo(props) {
  const car = useRef();
  const frontLeftTire = useRef();
  const frontRightTire = useRef();
  const rearLeftTire = useRef();
  const rearRightTire = useRef();

  const tl = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    tl.current.to(
      car.current.position,
      {
        duration: 5,
        x: 10,
        z: 10,
      },
      "car"
    );
    tl.current.to(
      frontLeftTire.current.rotation,
      {
        duration: 5,
        x: 10,
      },
      "car"
    );
    tl.current.to(
      frontRightTire.current.rotation,
      {
        duration: 5,
        x: 10,
      },
      "car"
    );
    tl.current.to(
      rearLeftTire.current.rotation,
      {
        duration: 5,
        x: 10,
      },
      "car"
    );
    tl.current.to(
      rearRightTire.current.rotation,
      {
        duration: 5,
        x: 10,
      },
      "car"
    );
  }, []);

  const { nodes, materials } = useGLTF("/models/lambo.glb");
  return (
    <group
      {...props}
      scale={0.015}
      rotation={[0, 0.8, 0]}
      position={[-5, 0, 0]}
      ref={car}
      dispose={null}
    >
      <group position={[0, 2.7, -119]}>
        {/* Rear Tire 1 */}
        <group
          ref={rearLeftTire}
          position={[-88.644, -40.871, -16.138]}
          rotation={[-Math.PI, 0, Math.PI]}
          scale={[1.605, 1.51, 1.51]}
        >
          <mesh
            geometry={nodes.RR_TiresGum_0.geometry}
            material={materials.TiresGum}
          />
          <mesh
            geometry={nodes.Whl_HD_FL_004_3_Universal_Wheel_0.geometry}
            material={materials.Universal_Wheel}
            scale={0.65}
          />
          <mesh
            geometry={nodes.Universal_Caliper_3_Universal_Wheel_0.geometry}
            material={materials.Universal_Wheel}
            position={[0.151, 0, 11.184]}
            rotation={[Math.PI, 0, -Math.PI]}
            scale={0.65}
          />
          <mesh
            geometry={nodes.wheel003_020_3_Chrome_0.geometry}
            material={materials.Chrome}
            position={[2.144, 0, 0]}
          />
          <mesh
            geometry={nodes.wheel003_019_3_Chrome_0.geometry}
            material={materials.Chrome}
            position={[5.388, 0, 0]}
          />
          <mesh
            geometry={nodes.wheel003_018_3_RimsChrome_0.geometry}
            material={materials.RimsChrome}
            position={[2.19, -0.315, -0.365]}
          />
          <mesh
            geometry={nodes.wheel003_015_3_BreakDiscs_0.geometry}
            material={materials.BreakDiscs}
            position={[1.998, 0, 0]}
          />
        </group>
        <group
          ref={rearRightTire}
          position={[88.644, -40.871, -16.138]}
          scale={[1.605, 1.51, 1.51]}
        >
          <mesh
            geometry={nodes.RL_TiresGum_0.geometry}
            material={materials.TiresGum}
          />
          <mesh
            geometry={nodes.Whl_HD_FL_004_2_Universal_Wheel_0.geometry}
            material={materials.Universal_Wheel}
            scale={0.65}
          />
          <mesh
            geometry={nodes.Universal_Caliper_2_Universal_Wheel_0.geometry}
            material={materials.Universal_Wheel}
            position={[-0.151, 0, -11.184]}
            scale={0.65}
          />
          <mesh
            geometry={nodes.wheel003_020_2_Chrome_0.geometry}
            material={materials.Chrome}
            position={[2.144, 0, 0]}
          />
          <mesh
            geometry={nodes.wheel003_019_2_Chrome_0.geometry}
            material={materials.Chrome}
            position={[5.388, 0, 0]}
          />
          <mesh
            geometry={nodes.wheel003_018_2_RimsChrome_0.geometry}
            material={materials.RimsChrome}
            position={[2.19, -0.315, -0.365]}
          />
          <mesh
            geometry={nodes.wheel003_015_2_BreakDiscs_0.geometry}
            material={materials.BreakDiscs}
            position={[1.998, 0, 0]}
          />
        </group>
        <group
          position={[-88.644, -40.871, 274.956]}
          rotation={[-Math.PI, 0, Math.PI]}
          scale={1.51}
          ref={frontLeftTire}
        >
          <mesh
            geometry={nodes.FR_TiresGum_0.geometry}
            material={materials.TiresGum}
          />
          <mesh
            geometry={nodes.Whl_HD_FL_004_1_Universal_Wheel_0.geometry}
            material={materials.Universal_Wheel}
            scale={0.65}
          />
          <mesh
            geometry={nodes.Universal_Caliper_1_Universal_Wheel_0.geometry}
            material={materials.Universal_Wheel}
            position={[-0.151, 0, -11.184]}
            scale={0.65}
          />
          <mesh
            geometry={nodes.wheel003_020_1_Chrome_0.geometry}
            material={materials.Chrome}
            position={[2.144, 0, 0]}
          />
          <mesh
            geometry={nodes.wheel003_019_1_Chrome_0.geometry}
            material={materials.Chrome}
            position={[5.388, 0, 0]}
          />
          <mesh
            geometry={nodes.wheel003_018_1_RimsChrome_0.geometry}
            material={materials.RimsChrome}
            position={[2.19, -0.315, -0.365]}
          />
          <mesh
            geometry={nodes.wheel003_015_1_BreakDiscs_0.geometry}
            material={materials.BreakDiscs}
            position={[1.998, 0, 0]}
          />
        </group>
        <group
          ref={frontRightTire}
          position={[88.644, -40.871, 274.956]}
          scale={1.51}
        >
          <mesh
            geometry={nodes.FL_TiresGum_0.geometry}
            material={materials.TiresGum}
          />
          <mesh
            geometry={nodes.Whl_HD_FL_004_Universal_Wheel_0.geometry}
            material={materials.Universal_Wheel}
            scale={0.65}
          />
          <mesh
            geometry={nodes.Universal_Caliper_Universal_Wheel_0.geometry}
            material={materials.Universal_Wheel}
            position={[0.151, 0, 11.184]}
            rotation={[Math.PI, 0, -Math.PI]}
            scale={0.65}
          />
          <mesh
            geometry={nodes.wheel003_020_Chrome_0.geometry}
            material={materials.Chrome}
            position={[2.144, 0, 0]}
          />
          <mesh
            geometry={nodes.wheel003_019_Chrome_0.geometry}
            material={materials.Chrome}
            position={[5.388, 0, 0]}
          />
          <mesh
            geometry={nodes.wheel003_018_RimsChrome_0.geometry}
            material={materials.RimsChrome}
            position={[2.19, -0.315, -0.365]}
          />
          <mesh
            geometry={nodes.wheel003_015_BreakDiscs_0.geometry}
            material={materials.BreakDiscs}
            position={[1.998, 0, 0]}
          />
        </group>
      </group>
      <group position={[0, 0, -119]}>
        <group
          position={[0, -44.015, 65.812]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={0.55}
        >
          <group
            position={[0.177, 97.714, -156.929]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          >
            <mesh
              geometry={nodes.yellow_WhiteCar_0.geometry}
              material={materials.WhiteCar}
            />
            <mesh
              geometry={nodes.yellow_Logo_0.geometry}
              material={materials.Logo}
            />
          </group>
          <group
            position={[0.124, 152.897, -194.053]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          >
            <mesh
              geometry={nodes.gloss_black_008_RimsChrome_0.geometry}
              material={materials.RimsChrome}
            />
            <mesh
              geometry={nodes.gloss_black_008_Mirror_0.geometry}
              material={materials.Mirror}
            />
          </group>
          <mesh
            geometry={nodes.silver_003_BreaksRedPaint_0.geometry}
            material={materials.BreaksRedPaint}
            position={[0, 38.861, 280.29]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.silver_002_ChromeBLurred_0.geometry}
            material={materials.ChromeBLurred}
            position={[0, 10.161, -116.09]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.silver_001_BreakDiscs_0.geometry}
            material={materials.BreakDiscs}
            position={[0.352, 130.351, 305.237]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.silver_ChromeBLurred_0.geometry}
            material={materials.ChromeBLurred}
            position={[0, 11.968, 292.626]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.matt_black_001_GreyElements_0.geometry}
            material={materials.GreyElements}
            position={[0.082, 36.83, 314.587]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.matt_black_FrameBlack_0.geometry}
            material={materials.FrameBlack}
            position={[0, 129.059, 29.085]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_050_BlackPaint_0.geometry}
            material={materials.BlackPaint}
            position={[97.377, 136.812, 284.925]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_049_BreakDiscs_1_0.geometry}
            material={materials.BreakDiscs_1}
            position={[0, 134.122, 287.404]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_046_BreakDiscs_1_0.geometry}
            material={materials.BreakDiscs_1}
            position={[0, 125.878, 254.503]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_045_BlackPaint_0.geometry}
            material={materials.BlackPaint}
            position={[134.452, 125.025, 267.18]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_044_BlackPaint_0.geometry}
            material={materials.BlackPaint}
            position={[144.589, 127.241, 255.248]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_043_BreakDiscs_1_0.geometry}
            material={materials.BreakDiscs_1}
            position={[0, 133.365, 271.34]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_042_BreakDiscs_1_0.geometry}
            material={materials.BreakDiscs_1}
            position={[0, 121.018, 262.467]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_040_Chrome_0.geometry}
            material={materials.Chrome}
            position={[0, 93.18, -497.126]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_033_Default_Material_0.geometry}
            material={materials.Default_Material}
            position={[141.975, 96.694, -474.547]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_027_BreakDiscs_1_0.geometry}
            material={materials.BreakDiscs_1}
            position={[0, 92.783, -496.746]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_024_BlackPaint_0.geometry}
            material={materials.BlackPaint}
            position={[-97.377, 136.812, 284.925]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_022_BreakDiscs_0.geometry}
            material={materials.BreakDiscs}
            position={[0, 126.693, 241.403]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_021_emitbrake_0.geometry}
            material={materials.emitbrake}
            position={[0, 128.601, 274.474]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_019_BlackPaint_0.geometry}
            material={materials.BlackPaint}
            position={[-134.452, 125.025, 267.18]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_018_BlackPaint_0.geometry}
            material={materials.BlackPaint}
            position={[-144.589, 127.241, 255.247]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_015_Hub_0.geometry}
            material={materials.material}
            position={[0, 95.296, -469.605]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_009_LightsFrontLed_0.geometry}
            material={materials.LightsFrontLed}
            position={[0, 90.942, -495.029]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_008_BreakDiscs_1_0.geometry}
            material={materials.BreakDiscs_1}
            position={[0, 86.076, -497.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_007_Default_Material_0.geometry}
            material={materials.Default_Material}
            position={[-141.975, 96.694, -474.547]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_002_BreakDiscs_0.geometry}
            material={materials.BreakDiscs}
            position={[0, 92.4, -499.12]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.lights_Hub_0.geometry}
            material={materials.material}
            position={[0, 150.589, -214.787]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.gloss_black_007_GreyElements_0.geometry}
            material={materials.GreyElements}
            position={[0, 179.623, -67.835]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.gloss_black_006_GreyElements_0.geometry}
            material={materials.GreyElements}
            position={[-0.002, 54.489, -543.446]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.gloss_black_005_GreyElements_0.geometry}
            material={materials.GreyElements}
            position={[0, 30.247, 277.475]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.gloss_black_004_GreyElements_0.geometry}
            material={materials.GreyElements}
            position={[0, -6.843, -145.25]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.gloss_black_003_GreyElements_0.geometry}
            material={materials.GreyElements}
            position={[0, 109.505, -313.377]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.gloss_black_002_GreyElements_0.geometry}
            material={materials.GreyElements}
            position={[0, 64.206, -137.569]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.gloss_black_001_BlackPaint_0.geometry}
            material={materials.BlackPaint}
            position={[0, 130.707, 297.042]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.gloss_black_GreyElements_0.geometry}
            material={materials.GreyElements}
            position={[0, 6.461, -516.938]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.glass_005_LightsGlassBack_0.geometry}
            material={materials.LightsGlassBack}
            position={[0, 38.841, 281.622]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.glass_004_LightsGlassFront_0.geometry}
            material={materials.LightsGlassFront}
            position={[1.479, 129.697, 274.367]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.glass_003_Glass_0.geometry}
            material={materials.Glass}
            position={[-0.405, 174.329, -27.919]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.glass_002_LightsGlassFront_0.geometry}
            material={materials.LightsGlassFront}
            position={[0, 150.588, -214.804]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
          <mesh
            geometry={nodes.glass_001_LightsGlassFront_0.geometry}
            material={materials.LightsGlassFront}
            position={[-2.215, 92.712, -497.837]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={2.746}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/lambo.glb");
